
sudo: required
language: rust

rust:
    - stable

cache:
  - timeout: 360
  - cargo
  - directories:
      - src/amethyst/

addons:
  apt:
    packages:
      - libasound2-dev
      - cmake

before_install:
    - gem install jekyll
    - gem install jekyll-feed

script:
    - ./generate.sh
    - echo "www.amethyst.rs" > build/CNAME

after_success: |
    [ $TRAVIS_BRANCH = master ] &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    git config user.name "Travis CI Worker" &&
    git config user.email "name@example.com" &&
    sudo -H pip install ghp-import &&
    ghp-import -n -p -f -s -m "Building website" build/

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/d0a22aa55fe94ba11c00
        on_success: always
        on_failure: always
        on_start: never
