
sudo: required
dist: trusty
language: rust

rust:
    - stable

# Force third-party crates to persist from previous builds and update only when
# needed.
cache: cargo

# Install ALSA development libraries before compiling on Linux.
addons:
  apt:
    packages:
      - libasound2-dev

before_install:
    - gem install jekyll
    - gem install jekyll-feed

script:
    - ./generate.sh
    - echo "www.amethyst.rs" > build/CNAME

after_success: |
    [ $TRAVIS_BRANCH = master ] &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    cargo install ghp &&
    ghp build &&
    git config user.name "Travis CI Worker" &&
    git config user.email "name@example.com" &&
    git push -f https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/d0a22aa55fe94ba11c00
        on_success: always
        on_failure: always
        on_start: never
