[[redirects]]
from = "/book/latest"
to = "https://book.amethyst.rs/stable/"
status = 301

[[redirects]]
from = "/book/latest/*"
to = "https://book.amethyst.rs/stable/:splat"
status = 301

[[redirects]]
from = "/doc/latest/doc"
to = "https://docs-src.amethyst.rs/stable/"
status = 301

[[redirects]]
from = "/doc/latest/doc/*"
to = "https://docs-src.amethyst.rs/stable/:splat"
status = 301

[[redirects]]
from = "/book/master"
to = "https://book.amethyst.rs/master/"
status = 301

[[redirects]]
from = "/book/master/*"
to = "https://book.amethyst.rs/master/:splat"
status = 301

[[redirects]]
from = "/doc/master/doc/*"
to = "https://docs-src.amethyst.rs/master/:splat"
status = 301

[[redirects]]
from = "/doc/master/doc/*"
to = "https://docs-src.amethyst.rs/master/:splat"
status = 301

[[redirects]]
from = "/blog/*"
to = "/posts/:splat"

[[redirects]]
from = "/assets/amethyst.svg"
to = "https://amethyst.cdn.prismic.io/amethyst%2F3fbe7dbd-1352-45f4-b2cf-cfa99f852e0a_logo-filled.svg"
