[[redirects]]
from = "/book/latest"
to = "https://book.amethyst.rs/stable/"
status = 301

[[redirects]]
from = "/book/latest/*"
to = "https://book.amethyst.rs/stable/:splat"
status = 301

[[redirects]]
from = "/doc/latest/doc/amethyst"
to = "https://docs-src.amethyst.rs/stable/amethyst/"
status = 301

[[redirects]]
from = "/doc/latest/doc/amethyst/*"
to = "https://docs-src.amethyst.rs/stable/amethyst/:splat"
status = 301

[[redirects]]
from = "/book/master"
to = "https://book.amethyst.rs/master/"
status = 301

[[redirects]]
from = "/book/master/*"
to = "https://book.amethyst.rs/master/:splat"
status = 301

[[redirects]]
from = "/doc/master/doc/amethyst"
to = "https://docs-src.amethyst.rs/master/amethyst/"
status = 301

[[redirects]]
from = "/doc/master/doc/amethyst/*"
to = "https://docs-src.amethyst.rs/master/amethyst/:splat"
status = 301

[[redirects]]
from = "/blog/*"
to = "/posts/:splat"
